# Generated by Django 3.2.12 on 2022-08-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BloodPressure', models.CharField(max_length=10)),
                ('OxygenLevel', models.IntegerField()),
                ('Swaptype', models.CharField(max_length=15)),
                ('measuredDateTime', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CovidReportApp.patients')),
            ],
        ),
    ]
